version: '3.1'

networks:
    frontend:
        driver: ${NETWORKS_DRIVER}
    backend:
        driver: ${NETWORKS_DRIVER}

volumes:
    qbittorrent:
        driver: ${VOLUMES_DRIVER}
    nginx:
        driver: ${VOLUMES_DRIVER}
    plex:
        driver: ${VOLUMES_DRIVER}


services:
    qbittorrent:
        image: linuxserver/qbittorrent:${QB_VERSION}
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - ${QB_HOST_ROOT_PATH}/config:/config
            - ${QB_HOST_ROOT_PATH}/torrents:/torrents
            - ${MEDIA_HOST_ROOT_PATH}:/media
            - ${DOWNLOADS_HOST_ROOT_PATH}:/downloads
        ports:
            - ${QB_WEBUI_HOST_PORT}:8080
            - ${QB_CLIENT_HOST_TCP_PORT}:6881/tcp
            - ${QB_CLIENT_HOST_UDP_PORT}:6881/udp


    nginx:
        image: lscr.io/linuxserver/nginx:${NGINX_VERSION}
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - ${NGINX_CONFIG_HOST_PATH}:/config
            - ${APP_CODE_PATH_HOST}:/config/www
        ports:
            - ${NGINX_HTTP_HOST_PORT}:80
            - ${NGINX_HTTPS_HOST_PORT}:443

    plex:
        image: lscr.io/linuxserver/plex:${PLEX_DOCKER_VERSION}
        environment:
            - TZ=${TIMEZONE}
            - VERSION=${PLEX_SERVER_VERSION}
        volumes:
            - ${PLEX_CONFIG_HOST_PATH}:/config
            - ${MEDIA_HOST_ROOT_PATH}:/movies
        ports:
            - ${PLEX_WEBUI_HOST_PORT}:32400/tcp
