version: '3.1'

networks:
    frontend:
        driver: ${NETWORKS_DRIVER}
    backend:
        driver: ${NETWORKS_DRIVER}

volumes:
    qbittorrent:
        driver: ${VOLUMES_DRIVER}
    nginx:
        driver: ${VOLUMES_DRIVER}
    plex:
        driver: ${VOLUMES_DRIVER}
    jellyfin:
        driver: ${VOLUMES_DRIVER}
    bazarr:
        driver: ${VOLUMES_DRIVER}
    radarr:
        driver: ${VOLUMES_DRIVER}
    jackett:
        driver: ${VOLUMES_DRIVER}



services:
    qbittorrent:
        image: linuxserver/qbittorrent:${QB_VERSION}
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - ${QB_HOST_ROOT_PATH}/config:/config
            - ${QB_HOST_ROOT_PATH}/torrents:/torrents
            - ${MEDIA_HOST_ROOT_PATH}:/media
            - ${DOWNLOADS_HOST_ROOT_PATH}:/downloads
        ports:
            - ${QB_WEBUI_HOST_PORT}:8080
            - ${QB_CLIENT_HOST_TCP_PORT}:6881/tcp
            - ${QB_CLIENT_HOST_UDP_PORT}:6881/udp


    nginx:
        image: lscr.io/linuxserver/nginx:${NGINX_VERSION}
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - ${NGINX_CONFIG_HOST_PATH}:/config
            - ${APP_CODE_PATH_HOST}:/config/www
        ports:
            - ${NGINX_HTTP_HOST_PORT}:80
            - ${NGINX_HTTPS_HOST_PORT}:443

    # plex:
    #     image: lscr.io/linuxserver/plex:${PLEX_DOCKER_VERSION}
    #     environment:
    #         - TZ=${TIMEZONE}
    #         - VERSION=${PLEX_SERVER_VERSION}
    #     volumes:
    #         - ${PLEX_CONFIG_HOST_PATH}:/config
    #         - ${MEDIA_HOST_ROOT_PATH}:/movies
    #     ports:
    #         - ${PLEX_WEBUI_HOST_PORT}:32400/tcp

    jellyfin:
        image: lscr.io/linuxserver/jellyfin:${JELLYFIN_DOCKER_VERSION}
        environment:
            - TZ=${TIMEZONE}
            - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_URL} #optional
        volumes:
            - ${JELLYFIN_CONFIG_HOST_PATH}:/config
            - ${MEDIA_HOST_ROOT_PATH}:/data/movies
        ports:
            - ${JELLYFIN_HTTP_PORT}:8096
            - ${JELLYFIN_HTTPS_PORT}:8920 #optional
            - ${JELLYFIN_CLIENT_DISCOVERY_PORT}:7359/udp #optional
            - ${JELLYFIN_SERVICE_DISCOVERY_PORT}:1900/udp #optional

    bazarr:
        image: lscr.io/linuxserver/bazarr:${BAZARR_DOCKER_VERSION}
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - ${BAZARR_CONFIG_HOST_PATH}:/config
            - ${MEDIA_HOST_ROOT_PATH}:/movies
        ports:
            - ${BAZARR_PORT}:6767

    radarr:
        image: lscr.io/linuxserver/radarr:${RADARR_DOCKER_VERSION}
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - ${RADARR_CONFIG_HOST_PATH}:/config
            - ${MEDIA_HOST_ROOT_PATH}:/movies
            - ${RADARR_SUBTITLE_DOWNLOADS_PATH}:/downloads
        ports:
            - ${RADARR_PORT}:7878

    jackett:
        image: lscr.io/linuxserver/jackett:latest
        environment:
            - TZ=${TIMEZONE}
            - AUTO_UPDATE=${JACKETT_AUTO_UPDATE} #optional
            - RUN_OPTS=${JACKETT_RUN_OPTIONS} #optional
        volumes:
            - ${JACKETT_CONFIG_HOST_PATH}:/config
            - ${JACKETT_BLACKHOLE_DOWNLOADS_PATH}:/downloads
        ports:
            - ${JACKETT_PORT}:9117
